version: '2'
services:
  postgres:
    image: postgres:13
    container_name: kol_postgres
    environment:
      POSTGRES_DB: kol_postgres
      POSTGRES_USER: kol_use
      POSTGRES_PASSWORD: Kol-password%08-2024
    ports:
      - "5434:5432"
    volumes:
      - kol_postgres:/var/lib/postgresql/data

volumes:
  kol_postgres:
    driver: local